'
'  Copyright 2025 Sachin chaurasiya.
'
'  Licensed under the Apache License, Version 2.0 (the "License");
'  you may not use this file except in compliance with the License.
'  You may obtain a copy of the License at
'
'      http://www.apache.org/licenses/LICENSE-2.0
'
'  Unless required by applicable law or agreed to in writing, software
'  distributed under the License is distributed on an "AS IS" BASIS,
'  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'  See the License for the specific language governing permissions and
'  limitations under the License.
'
'  ---------------------------------------------------------------------------
'  File : Alloting_g.java
'  description : handles the client side operation, using the features like 
'  regestration,alloting room,managing and viewing records of guest and rooms
'  Author : Sachin Chaurasiya  
'  Created : August 2025


' click alt + D to view the arhitecture of the whole project,
' to view the project without any problem download plantUML extension from the 
' extensions and download the graphicviz file
' from the internet. 
' any class or unique file you are adding and deleting must be added in this uml so that
' it can improve the architecture 
' of the program and others can also understand it.

@startuml architecture

skinparam linetype ortho
package HMS_module as HMS {
    class Mainfile {
        + register()
        + Allotroom()
        + Viewrecords() 
        + Managerecords()
        # database()
    }
}

package register_model as Register {
    class guest_rec {
        + register_guest()
    }
    class Innerguest_rec{
        -id : int
        -name : String
        -address : String
        -numberofpartners : int
        -phone : String
        -checkin : Date
        -checkout : Date
    }
}

package database_repository as Database {
    class dataconn{
        #initDatasource()
        #getConnection()
    }
}
package Alloting_modules as allot{
    class Alloting_g{
        -room_no : int
        -id :int
        -type : String
        -rate : String
        -status : String

    }
}
package Management as manage{
    class view_g_data{
        +View_g_record()
        +view_r_status()
    }
    class updaterec_g{
        +update_g_rec
        +update_a_rec
    }
    class deleterec_g{
        +delete_g_rec
    }
}

HMS -right-> Register
HMS <-up- Database 
allot<-down-Register
@enduml
